### ISSUE TITLE
Get catalogues error using api_key

### ISSUE THREAD

**Issue by danieluyo** [Paybook/sync-php#1]
In the site docs says:
> Obtén o muestra el catálogo del sitio con los endpoints /catálogos.
Nota: Los endpoints de /v1/catalogues aceptan sesiones de usuario (token) o la api_key

So im try:
```
$sites = Catalogues::get_sites(null, null, ['api_key'=>env('PAYBOOK_KEY')], true);
// and
$sites = Catalogues::get_sites(env('PAYBOOK_KEY'));
```
The result: Errors
```
(1/1) ErrorException
Trying to get property of non-object
in Catalogues.php (line 80)
at HandleExceptions->handleError(8, 'Trying to get property of non-object', 'fullpath/vendor/paybook/paybook/src/paybook/Catalogues.php', 80, array('session' => null, 'id_user' => null, 'options' => array('api_key' => 'API_KEY'), 'is_test' => true, 'params' => array('api_key' => 'API_KEY')))
in Catalogues.php (line 80)

//Other one

(1/1) ErrorException
Trying to get property of non-object
in Catalogues.php (line 80)
at HandleExceptions->handleError(8, 'Trying to get property of non-object', 'fullpath/vendor/paybook/paybook/src/paybook/Catalogues.php', 80, array('session' => 'API_KEY', 'id_user' => null, 'options' => array(), 'is_test' => true, 'params' => array()))
in Catalogues.php (line 80)

```

**Comment by hugoochoa** [comment]
Hi Daniel. The current ways of executing that method are:

1. By using a session object (first param):
    
    `$sites = paybook\Catalogues::get_sites($session);`

2. Or by passing a string with the value of the user's id `$id_user` (second param). In this case the call will be done by using the **API key** you used to init the library when executed `paybook\Paybook::init($api_key)`. **Hence, it is not necessary to pass the **API key** through the third param.** 

   ` $sites = paybook\Catalogues::get_sites(null, $id_user);`

We are working in a new version of this library where you'll be able to call this method without needing `$id_user` and only by using your **API key**, but now the only ways to consume that method are the ones described above.

Thanks for your report. 

**P.D.** The issue you're experiencing is due to you're not passing neither `$id_user` nor `$session`.

**Comment by danieluyo** [comment]
¿Any idea for when the new version of this library should be released? 
Im rewritting this lib :'v
